export interface Currency {
  code: string;
  symbol: string;
  name: string;
}

export const WORLD_CURRENCIES: Currency[] = [
  { code: "BRL", symbol: "R$", name: "Real brasileiro (R$)" },
  { code: "USD", symbol: "$", name: "Dólar americano ($)" },
  { code: "EUR", symbol: "€", name: "Euro (€)" },
  { code: "GBP", symbol: "£", name: "Libra esterlina (£)" },
  { code: "JPY", symbol: "¥", name: "Iene japonês (¥)" },
  { code: "CHF", symbol: "CHF", name: "Franco suíço (CHF)" },
  { code: "CAD", symbol: "C$", name: "Dólar canadense (C$)" },
  { code: "AUD", symbol: "A$", name: "Dólar australiano (A$)" },
  { code: "CNY", symbol: "¥", name: "Yuan chinês (¥)" },
  { code: "ARS", symbol: "$", name: "Peso argentino ($)" },
  { code: "MXN", symbol: "$", name: "Peso mexicano ($)" },
  { code: "CLP", symbol: "$", name: "Peso chileno ($)" },
  { code: "COP", symbol: "$", name: "Peso colombiano ($)" },
  { code: "UYU", symbol: "$", name: "Peso uruguaio ($)" },
  { code: "PEN", symbol: "S/.", name: "Sol peruano (S/.)" },
  { code: "PYG", symbol: "₲", name: "Guarani paraguaio (₲)" },
  { code: "BOB", symbol: "Bs", name: "Boliviano (Bs)" },
  { code: "VES", symbol: "Bs.S", name: "Bolívar venezuelano (Bs.S)" },
  { code: "INR", symbol: "₹", name: "Rúpia indiana (₹)" },
  { code: "RUB", symbol: "₽", name: "Rublo russo (₽)" },
  { code: "ZAR", symbol: "R", name: "Rand sul-africano (R)" },
  { code: "KRW", symbol: "₩", name: "Won sul-coreano (₩)" },
  { code: "TRY", symbol: "₺", name: "Lira turca (₺)" },
  { code: "SAR", symbol: "SR", name: "Riyal saudita (SR)" },
  { code: "AED", symbol: "AED", name: "Dirham dos EAU (AED)" },
  { code: "ILS", symbol: "₪", name: "Novo shekel israelense (₪)" },
  { code: "NZD", symbol: "NZ$", name: "Dólar neozelandês (NZ$)" },
  { code: "SGD", symbol: "S$", name: "Dólar de Singapura (S$)" },
  { code: "HKD", symbol: "HK$", name: "Dólar de Hong Kong (HK$)" },
  { code: "SEK", symbol: "kr", name: "Coroa sueca (kr)" },
  { code: "NOK", symbol: "kr", name: "Coroa norueguesa (kr)" },
  { code: "DKK", symbol: "kr", name: "Coroa dinamarquesa (kr)" },
  { code: "PLN", symbol: "zł", name: "Zloty polonês (zł)" },
  { code: "HUF", symbol: "Ft", name: "Florim húngaro (Ft)" },
  { code: "CZK", symbol: "Kč", name: "Coroa tcheca (Kč)" },
  { code: "THB", symbol: "฿", name: "Baht tailandês (฿)" },
  { code: "IDR", symbol: "Rp", name: "Rúpia indonésia (Rp)" },
  { code: "MYR", symbol: "RM", name: "Ringgit malaio (RM)" },
  { code: "PHP", symbol: "₱", name: "Peso filipino (₱)" },
  { code: "VND", symbol: "₫", name: "Dong vietnamita (₫)" },
  { code: "EGP", symbol: "E£", name: "Libra egípcia (E£)" },
  { code: "NGN", symbol: "₦", name: "Naira nigeriana (₦)" },
  { code: "PKR", symbol: "₨", name: "Rúpia paquistanesa (₨)" },
  { code: "BDT", symbol: "৳", name: "Taka bengali (৳)" },
  { code: "UAH", symbol: "₴", name: "Hryvnia ucraniano (₴)" },
  { code: "GEL", symbol: "₾", name: "Lari georgiano (₾)" },
  { code: "KZT", symbol: "₸", name: "Tenge cazaque (₸)" },
  { code: "MOP", symbol: "MOP$", name: "Pataca de Macau (MOP$)" },
  { code: "TWD", symbol: "NT$", name: "Novo dólar taiwanês (NT$)" },
  { code: "CRC", symbol: "₡", name: "Colón costarriquenho (₡)" },
  { code: "DOP", symbol: "RD$", name: "Peso dominicano (RD$)" },
  { code: "GTQ", symbol: "Q", name: "Quetzal guatemalense (Q)" },
  { code: "HNL", symbol: "L", name: "Lempira hondurenha (L)" },
  { code: "NIO", symbol: "C$", name: "Córdoba nicaraguense (C$)" },
  { code: "PAB", symbol: "B/.", name: "Balboa panamenha (B/.)" },
  { code: "CUP", symbol: "₱", name: "Peso cubano (₱)" },
  { code: "JMD", symbol: "J$", name: "Dólar jamaicano (J$)" },
  { code: "TTD", symbol: "TT$", name: "Dólar de Trinidad e Tobago (TT$)" },
  { code: "BHD", symbol: "BD", name: "Dinar bareinita (BD)" },
  { code: "KWD", symbol: "KD", name: "Dinar kuwaitiano (KD)" },
  { code: "OMR", symbol: "OR", name: "Rial omanense (OR)" },
  { code: "QAR", symbol: "QR", name: "Riyal catariano (QR)" },
  { code: "JOD", symbol: "JD", name: "Dinar jordaniano (JD)" },
  { code: "LBP", symbol: "L£", name: "Libra libanesa (L£)" },
  { code: "IQD", symbol: "ID", name: "Dinar iraquiano (ID)" },
  { code: "SYP", symbol: "LS", name: "Libra síria (LS)" },
  { code: "YER", symbol: "YR", name: "Riyal iemenita (YR)" },
  { code: "IRR", symbol: "IR", name: "Rial iraniano (IR)" },
  { code: "AFN", symbol: "؋", name: "Afegane afegão (؋)" },
  { code: "NPR", symbol: "₨", name: "Rúpia nepalesa (₨)" },
  { code: "LKR", symbol: "₨", name: "Rúpia do Sri Lanka (₨)" },
  { code: "MVR", symbol: "Rf", name: "Rupia das Maldivas (Rf)" },
  { code: "KHR", symbol: "៛", name: "Riel cambojano (៛)" },
  { code: "LAK", symbol: "₭", name: "Kip laosiano (₭)" },
  { code: "MMK", symbol: "K", name: "Kyat de Mianmar (K)" },
  { code: "MNT", symbol: "₮", name: "Tugrik mongol (₮)" },
  { code: "AMD", symbol: "֏", name: "Dram armênio (֏)" },
  { code: "AZN", symbol: "₼", name: "Manat azerbaijano (₼)" },
  { code: "BYN", symbol: "Br", name: "Rublo bielorrusso (Br)" },
  { code: "MDL", symbol: "L", name: "Leu moldávio (L)" },
  { code: "RSD", symbol: "din", name: "Dinar sérvio (din)" },
  { code: "BAM", symbol: "KM", name: "Marco conversível da Bósnia (KM)" },
  { code: "ALL", symbol: "L", name: "Lek albanês (L)" },
  { code: "MKD", symbol: "den", name: "Denar macedônio (den)" },
  { code: "ISK", symbol: "kr", name: "Coroa islandesa (kr)" },
  { code: "KGS", symbol: "som", name: "Som quirguiz (som)" },
  { code: "TJS", symbol: "SM", name: "Somoni tajique (SM)" },
  { code: "TMT", symbol: "m", name: "Manat turcomeno (m)" },
  { code: "UZS", symbol: "so'm", name: "Som uzbeque (so'm)" },
  { code: "KES", symbol: "KSh", name: "Xelim queniano (KSh)" },
  { code: "UGX", symbol: "USh", name: "Xelim ugandense (USh)" },
  { code: "TZS", symbol: "TSh", name: "Xelim tanzaniano (TSh)" },
  { code: "RWF", symbol: "FRw", name: "Franco ruandês (FRw)" },
  { code: "BIF", symbol: "FBu", name: "Franco burundundês (FBu)" },
  { code: "ETB", symbol: "Br", name: "Birr etíope (Br)" },
  { code: "SOS", symbol: "Sh.So.", name: "Xelim somali (Sh.So.)" },
  { code: "GHS", symbol: "GH₵", name: "Cedi ganês (GH₵)" },
  { code: "SLL", symbol: "Le", name: "Leone de Serra Leoa (Le)" },
  { code: "LRD", symbol: "LD$", name: "Dólar liberiano (LD$)" },
  { code: "GMD", symbol: "D", name: "Dalasi gambiano (D)" },
  { code: "MZN", symbol: "MT", name: "Metical moçambicano (MT)" },
  { code: "AOA", symbol: "Kz", name: "Kwanza angolano (Kz)" },
  { code: "ZMW", symbol: "ZK", name: "Kwacha zambiano (ZK)" },
  { code: "MWK", symbol: "MK", name: "Kwacha do Malawi (MK)" },
  { code: "BWP", symbol: "P", name: "Pula de Botswana (P)" },
  { code: "NAD", symbol: "N$", name: "Dólar namibiano (N$)" },
  { code: "SZL", symbol: "L", name: "Lilangeni da Suazilândia (L)" },
  { code: "LSL", symbol: "L", name: "Loti do Lesoto (L)" },
  { code: "CVE", symbol: "Esc", name: "Escudo cabo-verdiano (Esc)" },
  { code: "STD", symbol: "Db", name: "Dobra de São Tomé (Db)" },
  { code: "SCR", symbol: "SR", name: "Rupia das Seychelles (SR)" },
  { code: "MUR", symbol: "Rs", name: "Rupia mauriciana (Rs)" },
  { code: "MGA", symbol: "Ar", name: "Ariary malgaxe (Ar)" },
  { code: "KMF", symbol: "CF", name: "Franco comoriano (CF)" },
  { code: "DJF", symbol: "Fdj", name: "Franco djibutiano (Fdj)" },
  { code: "ERN", symbol: "Nfk", name: "Nakfa eritreu (Nfk)" },
  { code: "SDG", symbol: "SDG", name: "Libra sudanesa (SDG)" },
  { code: "MAD", symbol: "DH", name: "Dirham marroquino (DH)" },
  { code: "DZD", symbol: "DA", name: "Dinar argelino (DA)" },
  { code: "TND", symbol: "DT", name: "Dinar tunisiano (DT)" },
  { code: "LYD", symbol: "LD", name: "Dinar líbio (LD)" },
  { code: "XOF", symbol: "CFA", name: "Franco CFA da África Ocidental (CFA)" },
  { code: "XAF", symbol: "FCFA", name: "Franco CFA da África Central (FCFA)" },
  { code: "CDF", symbol: "FC", name: "Franco congolês (FC)" },
  { code: "FJD", symbol: "FJ$", name: "Dólar de Fiji (FJ$)" },
  { code: "PGK", symbol: "K", name: "Kina de Papua Nova Guiné (K)" },
  { code: "SBD", symbol: "SI$", name: "Dólar das Ilhas Salomão (SI$)" },
  { code: "VUV", symbol: "VT", name: "Vatu de Vanuatu (VT)" },
  { code: "TOP", symbol: "T$", name: "Paʻanga de Tonga (T$)" },
  { code: "WST", symbol: "WS$", name: "Tala samoano (WS$)" },
  { code: "BBD", symbol: "Bds$", name: "Dólar de Barbados (Bds$)" },
  { code: "BSD", symbol: "B$", name: "Dólar das Bahamas (B$)" },
  { code: "BZD", symbol: "BZ$", name: "Dólar de Belize (BZ$)" },
  { code: "KYD", symbol: "CI$", name: "Dólar das Ilhas Cayman (CI$)" },
  { code: "GYD", symbol: "G$", name: "Dólar da Guiana (G$)" },
  { code: "SRD", symbol: "SRD", name: "Dólar do Suriname (SRD)" },
  { code: "HTG", symbol: "G", name: "Gourde haitiano (G)" },
  { code: "AWG", symbol: "Afl.", name: "Florim de Aruba (Afl.)" },
  { code: "ANG", symbol: "NAƒ", name: "Florim das Antilhas (NAƒ)" },
  { code: "BND", symbol: "B$", name: "Dólar do Brunei (B$)" },
  { code: "XCD", symbol: "EC$", name: "Dólar do Caribe Oriental (EC$)" },
  { code: "FKP", symbol: "FK£", name: "Libra das Ilhas Malvinas (FK£)" },
  { code: "SHP", symbol: "SH£", name: "Libra de Santa Helena (SH£)" },
  { code: "GIP", symbol: "GIP", name: "Libra de Gibraltar (GIP)" }
];

export function formatCurrency(amount: number, symbol: string = "R$") {
  const formattedNum = amount.toLocaleString("pt-BR", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2
  });
  return `${symbol} ${formattedNum}`;
}
